---
#Descargar fuentes de github
#- name: Descargando {{ nagios_version }}
#  get_url:
#    dest: '{{ download_dir_nagios }}/'
#    url: https://github.com/NagiosEnterprises/nagioscore/releases/download/{{ nagios_version }}/{{ nagios_version }}.tar.gz

- name: Copiando codigo fuente {{ nagios_version }}
  copy:
    src: /tmp/{{ nagios_version }}.tar.gz
    dest: '{{ download_dir_nagios }}'

#Desempaquetando fuentes
- name: Desempaquetando {{ nagios_version }}
  unarchive:
    src: '{{ download_dir_nagios }}/{{ nagios_version }}.tar.gz'
    dest: '{{ download_dir_nagios }}'
    remote_src: yes

- name: Deteniendo nagios
  service:
    name: nagios
    state: stopped

#iniciando compilacion
- name: Configure nagios core
  command: sh configure --with-command-group={{ group_admin }}
  args:
    chdir: '{{ download_dir_nagios }}/{{ nagios_version }}' 

- name: Configure nagios core - make all
  make:
    chdir: '{{ download_dir_nagios }}/{{ nagios_version }}' 
    target: all
    params:
      NUM_THREADS: '{{ ansible_processor_vcpus }}'

- name: Configure nagios core - make install
  make:
    chdir: '{{ download_dir_nagios }}/{{ nagios_version }}'
    target: install
    params:
      NUM_THREADS: '{{ ansible_processor_vcpus }}'

- name: Configure nagios core - make install-init
  make:
    chdir: '{{ download_dir_nagios }}/{{ nagios_version }}'
    target: install-init
    params:
      NUM_THREADS: '{{ ansible_processor_vcpus }}'

- name: Eliminando {{ nagios_version }}.tar.gz
  file:
    path: '{{ download_dir_nagios }}/{{ nagios_version }}.tar.gz'
    state: absent

- name: Iniciando nagios
  systemd:
    name: nagios
    state: started
    daemon_reload: yes
  tags: ng
...
